spring.application.name=jobtrackpro

spring.datasource.url=jdbc:postgresql://localhost:5432/jobtrack
spring.datasource.username=postgres
spring.datasource.password=2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8080

jwt.secret=jobtrack_super_secret_key
jwt.expiration=3600000

